### ISSUE TITLE
Weird behavior with buttonsets

### ISSUE THREAD

**Issue by KYSXD** [BoomerangAide/GPTP-For-VS2008#12]
In the last version (update 3) there is a bug:

Can't use the sub - button sets (like the SCV's basic buildings), because after a few seconds the game changes the displayed buttons to the first ones (the basic ones).

**Edit:**
It seems that the bug is caused by the buttonset hook. No problem when commenting them on initialize.cpp

**Comment by BoomerangAide** [comment]
Argh, it's coming from that recently enabled "updateCurrentButtonset" function.
Maybe I should have really dropped it.
I will look into it later, but a temporary way to fix the issue by disabling that function is to comment out "jmpPatch(updateCurrentButtonsetWrapper,       Func_UpdateCurrentButtonset, 6);" in buttonsets_inject.cpp

**Comment by BoomerangAide** [comment]
Ok, I had the *IS_IN_REPLAY condition understood backward.
Should be fixed now.
Thanks for reporting the bug.
