### ISSUE TITLE
Possible issue with Update 3.999

### ISSUE THREAD

**Issue by BoomerangAide** [BoomerangAide/GPTP-For-VS2008#17]
My Internet was cut in the middle of an update.
The current files may not work.
I apologize about it.
I will fix things as soon as my Internet is back for my desktop pc.

**Comment by BoomerangAide** [comment]
Due to the circumstances listed in the previous comment, it's possible bugs may be left due to the update being cut in 2 parts.
Please report any anomaly if something happen.

**Comment by KYSXD** [comment]
I got some errors with the version 3.999/4.0:
`error C2511: 'void CUnit::orderTo(u8,CUnit *)' : overloaded member function not found in 'CUnit'
1>        c:\...\gptp-for-vs2008\gptp\scbw\structures\cunit.h(10) : see declaration of 'CUnit'`

`error C2664: 'scbw::canWeaponTargetUnit' : cannot convert parameter 2 from 'const CUnit *' to 'CUnit *'
1>        Conversion loses qualifiers`

Is a problem with the update or just me?

**Comment by BoomerangAide** [comment]
Should be fixed.
All "const CUnit*" should be turned into "CUnit*", and for some reason, CUnit.h and CUnit.cpp were not updated properly.
Thanks for reporting.

**Comment by KYSXD** [comment]
Not trying to be annoying, but i downloaded the last GPTP version (4.001) to see if my changes were the ones that messed up the files, but still got this problems:

[LastBuild.txt](https://github.com/BoomerangAide/GPTP-For-VS2008/files/501890/LastBuild.txt)

:P

**Comment by BoomerangAide** [comment]
Indeed, it's those AI files.Even disabled, they still cause trouble.I will probably remove them completely in a later version.
For now, I tried to upload the versions I'm using to fix stuff.
My comparer isn't helpful to locate issues, as there are space/tabs/endline differences in the downloaded files so real differences can't be located through it.
Thanks again for reporting.
