### ISSUE TITLE
Possible Issue with Unit_Train hook

### ISSUE THREAD

**Issue by KYSXD** [BoomerangAide/GPTP-For-VS2008#19]
It seems that the train unit hook causes the building to queue the unit without setting the build order.

It also seems to happen after training some units and creating a new building.

Disabling this hook fixes this problem (so far).

**Comment by BoomerangAide** [comment]
I'm not sure I understand.
How do I reproduce and see the issue?

**Comment by BoomerangAide** [comment]
I changed something in the unit train hook in Version 4.008.
Maybe now it's working properly?

**Comment by KYSXD** [comment]
Yeah, working right now.
(Still haven't figured out why.)
Thanks!
