### ISSUE TITLE
Consume max energy comparison is incorrect

### ISSUE THREAD

**Issue by Voyager7456** [BoomerangAide/GPTP-For-VS2008#20]
wpnspellhit.cpp, in ConsumeHit:

     if((energyMax - attacker->energy) > 12800) //12800 is 50 energy ingame
                   attacker->energy = energyMax;
               else
                   attacker->energy += 12800;

The conditions should be reversed.

**Comment by BoomerangAide** [comment]
Fixed in version 4.009
