### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by RavenWolflisk** [BoomerangAide/GPTP-For-VS2008#21]
Hi BoomerangAide, 
First of all thanks a lot for your work updating GPTP, its really appreciated.

I have a problem using the new burrow tech hooks, basically the functions seems to never execute (or im missing something?)
I have called the hooks::injectBurrowTechHooks(); in the initialize.cpp, but when i burrow / unburrow units in the mod nothing change… (I tried print text at the begin of each function, setting units hp to 1, but nothing happens) Also tested with a clean mod and only that hook injected

And some minor mistakes
-In the recall_spell.cpp: the energy cost must be multiplied by 256 when checking if there is enough energy and when the energy cost is subtracted (lines 163 and 199)
-And in hallucination_spell.cpp: line 43 have counter == 0; where it should be counter = 0;

And finally, a request. It is possible to inject the code when the target position of the orders are given to units by the user? Specifically, I would like to change the target point assigned to units when a spell is issued to multiple units

**Comment by BoomerangAide** [comment]
Hi,

Thanks for the reports.
For recall, I checked and there's no mistake, there's no multiplication to do in these cases.
For hallucination, I will fix it in my offline code and update it later online, thanks for the fix.
For burrow, it's more complicated, I tried taking functions that were most likely to produce the final burrow effect, but maybe I'm misunderstanding  how CMDRECV functions are used, making the hooks useless.
For the request, maybe it's BTNSACT_UseTech that I would have to hook, but it is a function very different to others, so I don't know yet what I could do, but I will try.

**Comment by RavenWolflisk** [comment]
Are you sure that is not need to multiply the energy cost? I have tested without it and only subtract less than 1 energy if i have energy to cast the spell

Without multiplying the values, you still get the enough energy message as it seems that there is a previous validation when you press the button. 

Also in the cast_order.cpp, the energy is multiplied before checking or calling the spendUnitEnergy function
line 76: spellCost = techdata_dat::EnergyCost[techUsed] * 256;

**Comment by BoomerangAide** [comment]
You were right about recall energy cost, I found where my mistake was.

**Comment by BoomerangAide** [comment]
About BTNSACT_UseTech, it wasn't the answer, it prepares the order to be given, but don't give it (because after clicking a command, you can cancel instead of clicking a target).
I don't know what function validate when clicking a target, so I can't create a hook.

**Comment by RavenWolflisk** [comment]
Well, thanks for giving it a try. 
What about some of these ones?
CMDACT_TargetOrder 004C0300 00000077
CMDACT_RightClickOrder 004C0380 00000074
input_targetOrder_LeftMouseClick 004BD500 00000074
issueTriTargetOrder 0048CAF0 00000051

**Comment by KYSXD** [comment]
I think the approach could be a little different.

Maybe analizing how
CMDACT_Stop 004233F0 0000001C
works could give a hint. (since is an easy order that sends a command to each unit in the selection without the need of a right-click)

By looking in the assembler it looks like it calls
QueueGameCommand 00485BD0 0000009C

Maybe that last function (or the call to it within another) could be the one behind the magic.

**Comment by RavenWolflisk** [comment]
Doing some testing I was able to make the burrow hooks to work (or at least it seems to be working on my mod)
But there is a problem in CMDRECV_Burrow, seems like the function_004754F0 is not doing what is supposed to do, and instead every unit commanded to burrow will die after calling it, i have replaced the call to the function with selected_unit->orderTo(OrderId::Burrow); for testing purposes (i know there are other stuff is nedded to do) and is "working"

Tested on a 1 vs 1 multiplayer game and the functions runs for every player

I replaced the Memory offsets in the injectBurrowTechHooks with the ones taken from https://github.com/furion85/vgce/blob/master/data/Blizzard/Starcraft/1161_Functions_All.txt

So here is the injectBurrowTechHooks updated
	void injectBurrowTechHooks() {
		//jmpPatch(CMDRECV_UnburrowWrapper,	0x004E8C20, 3);
		jmpPatch(CMDRECV_UnburrowWrapper,	0x004C1AC0, 3);
		//jmpPatch(CMDRECV_BurrowWrapper,		0x004EA180, 6);
		jmpPatch(CMDRECV_BurrowWrapper,		0x004C1FA0, 6);
		//jmpPatch(Unburrow_ProcWrapper,		0x004EA3E0, 1);
		jmpPatch(Unburrow_ProcWrapper,		0x004E97C0, 1);
	}
In my case i just nedd to add code to the  CMDRECV_Unburrow funtion, so its working fine for me

**Comment by BoomerangAide** [comment]
Thanks a lot for the feedback.
I fixed burrow techs hooks, should be working now.
I will have a look at those functions for assigning order later, thanks for them.

**Comment by RavenWolflisk** [comment]
Some more bugs:
EMP Shockwave does not remove shields if WpnSpellHit is enabled
In the condition: if(current_unit != attacker && (attacker == NULL || current_unit == attacker->subunit)) there is a “!” missing after the && or what is the same (and more legible for me):
if(current_unit != attacker && (attacker !=NULL && current_unit != attacker->subunit))

In appi.cpp the funtion MoveScreenToUnit() have some coords mistakes
y = (s16)unit->sprite->position.x; 
Should be
y = (s16)unit->sprite->position.y;

And 
x = ((x/32) - 6) * 32;
y = ((y/32) - 10) * 32;
Should be
x = ((x/32) - 10) * 32;
y = ((y/32) - 6) * 32;

In cast_feedbak, the call to createOverlay() should be replaced for createTopOverlay(). The first cause that feedbak overlay plays beetwen Dark Archon body and energy ball. The last works like in vanilla, making the overlay over the whole archon

And The unitCanSeeCloakedTarget function in attack_orders.cpp should be called unitCantSeeCloakedTarget instead

**Comment by BoomerangAide** [comment]
Thanks for feedback.
Will be fixed in next version (4.014)

**Comment by BoomerangAide** [comment]
About "_And finally, a request. It is possible to inject the code when the target position of the orders are given to units by the user? Specifically, I would like to change the target point assigned to units when a spell is issued to multiple units_" it should be possible with the new Receive Command hook, but the function is quite complex, and trial and error will be needed to find how it work on a specific case.

**Comment by RavenWolflisk** [comment]
Great! This will be very usefull. 
Thanks again for your work on this
