### ISSUE TITLE
Optical Flare crashes the game when cast

### ISSUE THREAD

**Issue by Voyager7456** [BoomerangAide/GPTP-For-VS2008#22]
Casting Optical Flare on a unit appears to crash the game.

**Comment by BoomerangAide** [comment]
Are you sure you're using the latest Update-4 branch version?
If yes, I could not reproduce the issue, I may need more information on how to perform the actions that crash the game.

**Comment by Voyager7456** [comment]
Sorry, finally got around to this. Yes, I'm using the latest Update-4 branch version. 

The action appears to be just create a Medic, research Optical Flare, cast it on any unit. Results in an invalid read at 0x0048edaf. The only hook that needs to be enabled for this is the WpnSpellHit hook.

**Comment by RavenWolflisk** [comment]
Confirmed optical flare crash: Start custom map with medics, use "medieval man" cheat, cast optical flare on any unit and game crash when missile hit the target.
The target that receive the OpticalFlareHit fuction seems to be invalid (when i log the target->id is 292, which dont correspond to any unit...)
The bullet->attackTarget.unit is correct and can be fixed using that value

**Comment by BoomerangAide** [comment]
Fixed I think.
For some reason, an update wasn't applied to the online files.
I've copied the full files content to make sure all bugfixes are updated this time.
