### ISSUE TITLE
Medic crashes the game when ordered to attack in a group

### ISSUE THREAD

**Issue by Voyager7456** [BoomerangAide/GPTP-For-VS2008#23]
If you have the Medic selected in a group of other units and order the group to attack a target, the game will crash when the Medic gets in range of the target.  This only occurs if MedicOrdersHooks is enabled.

**Comment by Voyager7456** [comment]
For the crash above, you need to target a specific unit. I've seen invalid reads at at least 2 addresses for this bug, one of which being instruction at 0x0043fbc9 read memory at 0x00000064.

I believe that this crash occurs when the Medic changes its order. Another crash I encountered was when I ordered a Medic to attack move in a group and it encountered a wounded unit along the way. When it went to heal the wounded unit, the game crashed. Looked like an NPD.

**Comment by BoomerangAide** [comment]
I was able to reproduce a crash in UED mission 2 (Dylarian Shipyards), that could be prevented by disabling the HealMove hook.
I will look into it.

edit: bugfix released that fix that case.Hopefully it fix it all.
