### ISSUE TITLE
Canceling all units in carrier's queue crashes the game

### ISSUE THREAD

**Issue by KYSXD** [BoomerangAide/GPTP-For-VS2008#26]
Removing all units in a carrier's queue crashes.

This doesn't happen with Reaver.

**Comment by BoomerangAide** [comment]
Commenting out **jmpPatch(secondaryOrd_TrainFighterWrapper,	0x00466790, 2);** in hooks\orders\unit_making\unit_train_inject.cpp seems to fix it, so I guess the issue is in the secondaryOrd_TrainFighter function.I'm looking into it.

**Comment by BoomerangAide** [comment]
Fixed in Version 4.020
