### ISSUE TITLE
Infestation hook cause crash

### ISSUE THREAD

**Issue by iquare** [BoomerangAide/GPTP-For-VS2008#29]
When the Command Center (or any other infestable unit) is destroyed while Queen is infesting it, the Queen doesn't reappear and the game crashes.

**Comment by BoomerangAide** [comment]
Thank you for the report.
I managed to reproduce the issue, and will start looking into what is causing it.

**Comment by BoomerangAide** [comment]
Fixed in Version 4.024
Sorry for the inconvenience.
