### ISSUE TITLE
Stats panel display inject is missing

### ISSUE THREAD

**Issue by Voyager7456** [BoomerangAide/GPTP-For-VS2008#33]
There's no jmpPatch in injectStatsPanelDisplayHook(). 

I tried adding my own, but when I attempted to select a unit I got an invalid access when selecting a unit:
Instruction at 0x00456c88 referenced memory at 0x00000000

Not sure if that's because I screwed up the jmpPatch or if there's an error in stats_panel_display()

**Comment by BoomerangAide** [comment]
Thanks for the report.
Given what's inside injectStatsPanelDisplayHook(), it is unfinished, so never tested properly, and the issue probably come from my code.
I will look into it.

**Comment by BoomerangAide** [comment]
Should be fixed in Version 4.104.
I'm leaving the issue open (at least) 1 week, and if there's no more problems, I will close it.
