### ISSUE TITLE
Mistake in building_morph hook

### ISSUE THREAD

**Issue by iquare** [BoomerangAide/GPTP-For-VS2008#37]
There's a mistake in "updateNewUnitVision" function call. It uses unit pointer, but it should use unit id instead.
Using hook in its current shape leads to bugs - creep doesn't properly spawn (it is very noticeable if building was placed near the map's edge), sometimes preplaced structures (spire in my example) crash once their morph is finished.

**Comment by BoomerangAide** [comment]
Thanks for your report.
I checked the entire function, and my base work, I don't understand how the type became wrong, but that's what happened.
Should be fixed now.
