### ISSUE TITLE
What hooks are you looking for?

### ISSUE THREAD

**Issue by BoomerangAide** [BoomerangAide/GPTP-For-VS2008#6]
Hi,

If there's a particular game feature you're interested in, you can leave a message here.
There are some things I would not be able to deal with, but for others, I may be able to get one or several hooks that would be enough to interact/interfere with the feature you're interested in.

Of course this may take time, but at least, there you can try asking.

**Comment by KYSXD** [comment]
Hi!.

Maybe you could work on the screen size.
Right now, SC engine only renders a 640px400p image:
http://www.moddb.com/members/kysxd/images/weird

Could you find a way to make the game render a fully 640x480??

Also, could you make more than 1 building selectable?
(And maybe after that, look for +12 units selection).

Greetings.

**Comment by BoomerangAide** [comment]
Hi,

First I want to say that this issue is about "hooks", not about implementing new features not existing in Starcraft.
Having a hook allow to change Starcraft behavior around it, but it may take lots of them for some features.

About your image, the image size is 640x480, and the minimap display show that Starcraft do display stuff at the bottom.
My guess is that you're trying to draw on the "game" layer stuff that belong to the "dialog" layer (layers are in structures\Layer.h), and that got Starcraft confused, especially since it's normally keeping those as nicely separated rectangles, and you're mixing those 2.
I don't think I can help on that, I already had to find when to stop for the buttonset hook because lots of drawing/interaction functions were too complicated (lots of calls, access to unidentified areas of memory, weird maths...) to be make into hooks, and what you need is probably even more complicated.

For selection, I will have a look to see if I can get hooks for it. 
Maybe it will be simple enough that removing something that exclude buildings from multi-selection would work for it.

+12 units selection is harder, since it (clientSelectionGroup) is using a hard-coded array.
Besides, it would require something not existing to view units beyond 12 (or another limit if Starcraft can actually make units wireframes smaller in selection view).

**Comment by KYSXD** [comment]
Hi!. Some questions/request.

There are some hooks for the AI on spells.
Any chance to make one for the harvest behavior (AI)?

Where can i modify the larva amount for buildings?
I want to make the Hatchery, Lair and Hive to spawn 3,4 and 5 larva.

I know there is an example of how to copy a button set.
Could you make and example of how to change the buttonset of a unit for a custom one?

Where is controlled the orderQueueTimer ?

Also, is possible to re-write the pathfinding?

Thank you.

**Comment by BoomerangAide** [comment]
Hi,

Could you move your questions to a separate issue?
It can take lots of space to reply, and it's being off topic for this specific issue.

I will try to answer once it's done, and I also have researched selection mechanisms and will be able to come back on that topic.

**Comment by KYSXD** [comment]
Recall hook! (Firegraft has support to modify this, but it would be cool to have one in GPTP).

Also, nydus "move unit" hook!

**Comment by KYSXD** [comment]
There's a unit_morph hooks that controls the variables during the process of morphing (like hydra-lurker and mutalisk morphs) but there's no building_morph equivalent (the current one only is used by AI purposes), could one be added?

**Comment by KYSXD** [comment]
(Added in new post to be able to delete this (individually) when answered)
Could be possible to add a hook to control the 'createBuildings' and 'createInitialUnits' on non-custom games?

**Comment by BoomerangAide** [comment]
Redoing new files made differently for the unit_morph and building_morph stuff is probably going to be one of the last things I do before finally uploading what I will call Update 3.99 (meaning last change before creating new branch Update 4).For the initial creation stuff, I will see when I reach Update 4.

**Comment by KYSXD** [comment]
Is it possible to add a hook for
GiveUnit 0049EFA0 000001C8
centerviewUnitGroup 004967E0 00000156 ?

**Comment by BoomerangAide** [comment]
I'm currently having a look at those CreateInitial* functions.

**Comment by BoomerangAide** [comment]
I created the GiveUnit hook, but I failed at centerviewUnitGroup.

**Comment by KYSXD** [comment]
Any chance to add a hook for...
unit_isUnselectable 0046ED80 00000024?
CMDRECV_UnitMorph 004C1990 00000124? (This may be a short one)
CMDRECV_MergeDarkArchon 004C0CD0 000001BA?
CMDRECV_MergeArchon 004C0E90 000001BA?

How about the CMDRECV_PlaceBuilding functions and/or CMDRECV_Build?

Thanks for all your work!

**Comment by KYSXD** [comment]
This two could be helpful, if possible.

SetCooperativeLevel 004BB600

Also, this one may be hard:

replayStatBtns 00427A80

**Edit**
This also: load_statbtn_BIN 00459B90

?? 4588C0 <- This is a short one, called by statBtn_dlg_CharPress 00458B30.

PS: Thanks in advance. n.n

**Comment by BoomerangAide** [comment]
I will have a look at that.

**Comment by BoomerangAide** [comment]
Requests from Voyager7456 added in Version 4.027.
Will remove the comments about it in a few days.
Now I will have a look at requests from KYSXD.

**Comment by BoomerangAide** [comment]
I managed to do the InitializeDialog function (went better than last time I attempted to touch one of those global dialog modification functions).
I suppose if you wanted to use it for extended button set by adding your functions calls in the C code, you would have to just do a check for (dlgFunc == 0x00459B00) to make sure it's the right dialog being processed...I hope it's not more complicated than that, but if it is indeed more complicated, your old code is probably fine.

**Comment by KYSXD** [comment]
Those new hooks are really helpful. As you said, I only needed to check for that address to make my patch and make +9 buttons available.

**Edit:**
Everything is working properly so far. I just needed to edit the functions array (in Version 4.101).
I added a custom BinDlg (edited the file StatBtnX.bin, where X is T, P, Z, N and added 3 dialogs (to each one) with button flags and ID from 10 to 12) and the loading process was successful.
This is easier than my last patch.

Thanks!!

**Comment by BoomerangAide** [comment]
About statbtn_DLG_Interact, the comments I forgot to remove (fixed now) in InitializeDialog were actually about it, the first 2 calls in InitializeDialog do nothing (don't write anywhere in memory and return true), and the last don't write anything directly but call other functions, that probably do stuff.
So I won't hook that one, but I will try to dig deeper to see what really do a job that would be interesting to modify.

**Comment by BoomerangAide** [comment]
In Version 4.101, I added a hook for statbtn_BIN_CustomCtrlID in the buttonsets hook, that allow to use a custom array that will then be used in registerUserDialogAction().
Now I don't have the other files needed to test extended button set, so I'm not sure how helpful it can be.
Possibly with an extended array, one should either not give the index 10 to a button and skip to 11 and above, or maybe use *IS_IN_REPLAY and use the old values instead of the custom array if in replay.
I studied many functions at many levels, and I think this one may be the most significant in the dialog initialization process.

**Comment by BoomerangAide** [comment]
Various CMDRECV_Build related hooks added in Version 4.102.
I should be able to clean up this issue a bit soon.
Still have to create, either an issue or a wiki page, about all the things I haven't hooked, why, and how much I studied them (I got those infos written already, but need to adapt some thing when I put it on Internet).

**Comment by KYSXD** [comment]
Any chance for this functions?

getNextNearestMineralsEx 004432D0
??? 004445E0 = FindMineralField(), edx resource_area

Thanks!

**Comment by BoomerangAide** [comment]
I will look into it.
I was just getting frustrated of not updating for a while, so it will give me a more significant opportunity.

**Comment by BoomerangAide** [comment]
Added somewhat in version 4.106, but it was so tightly tied to AI features that I wasn't quite in my element.
But maybe there are still interesting things to do with those if they do work properly without causing weird stuff (especially with the AI, a concern that made me disable the feature by default).

Note: due to my issues with github, this topic is now closed.
