### ISSUE TITLE
Some files aren't up to date.

### ISSUE THREAD

**Issue by KYSXD** [BoomerangAide/GPTP-For-VS2008#8]
GPTP/SCBW/scbwdata.h fix!
ButtonIcon isn't in orders_dat DatLoad structure.

**Comment by BoomerangAide** [comment]
Thanks, fixed it.
In the future, I think I will try to download the stuff, especially before merging into main branch, to check for this kind of issue.

**Comment by KYSXD** [comment]
Got some errors when compiling:

...\gptp\hooks\tech_target_check.cpp(57) : error C3861: 'isInfestableCC': identifier not found
...\gptp\scbw\structures\cunit.cpp(556) : error C2065: 'PLAYABLE_PLAYER_COUNT' : undeclared identifier
...\gptp\scbw\structures\player.cpp(34) : error C2065: 'PLAYABLE_PLAYER_COUNT' : undeclared identifier
...\gptp\initialize.cpp(67) : error C3861: 'injectInfestationHooks': identifier not found
...\gptp\initialize.cpp(67) : error C2039: 'injectInfestationHooks' : is not a member of 'hooks'
...\gptp\hooks\interface\buttonsets.cpp(360) : error C2653: 'BinDlgFlags' : is not a class or namespace name
...\gptp\hooks\interface\buttonsets.cpp(360) : error C2065: 'Visible' : undeclared identifier
...\gptp\hooks\interface\buttonsets.cpp(381) : error C2653: 'BinDlgFlags' : is not a class or namespace name
...\gptp\hooks\interface\buttonsets.cpp(381) : error C2065: 'Unknown0' : undeclared identifier
...\gptp\hooks\interface\buttonsets.cpp(382) : error C2653: 'BinDlgFlags' : is not a class or namespace name
...\gptp\hooks\interface\buttonsets.cpp(382) : error C2065: 'Unknown0' : undeclared identifier

It's me? or a problem with the files?

**Comment by BoomerangAide** [comment]
Wow, I can't believe I had so many updates...simply not done.Sorry.
I've actually done what I said (downloading the .zip), and I think this time the only thing not in sync with my local copy should be spaces, tab and newlines.
Thank you for reporting, I hope it will work this time.
